In [1]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.10/dist-packages (0.2.25)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.5.3)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.22.4)
Requirement already satisfied: requests>=2.26 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.27.1)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.10/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.9.3)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2022.7.1)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.3.8)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.11.2)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.26->yfinance) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.26->yfinance) (2023.7.22)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests>=2.26->yfinance) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.26->yfinance) (3.4)

Here is a comment for each line of code:

* Line 1: This line imports the yfinance package.
* Line 2: This line creates a list of DataFrames.
* Line 3: This line iterates over the tickers.
* Line 4: This line downloads the stock data for the current ticker.
* Line 5: This line adds the DataFrame to the list.
* Line 6: This line returns the list of DataFrames.

Here is a docstring for the function:

```
download_stocks(tickers: List[str]) -> List[pd.DataFrame]:

Downloads stock data from Yahoo Finance.

Args:
    tickers: A list of stock tickers.

Returns:
    A list of Pandas DataFrames, one for each stock.
```

In [ ]:
# Import the yfinance package.
import yfinance as yf
import pandas as pd
from typing import List

def download_stocks(tickers: List[str]) -> List[pd.DataFrame]:
    """
    Downloads stock data from Yahoo Finance.

    Args:
        tickers: A list of stock tickers.

    Returns:
        A list of Pandas DataFrames, one for each stock.
    """

    # Create a list of DataFrames.
    df_list = []

    # Iterate over the tickers.
    for ticker in tickers:
        # Download the stock data.
        df = yf.download(ticker)

        # Add the DataFrame to the list.
        df_list.append(df)

    return df_list

In [ ]:
list_of_stocks = download_stocks(['GOOGL', 'MSFT'])

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [ ]:
list_of_stocks[0]

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2004-08-19,2.502503,2.604104,2.401401,2.511011,2.511011,893181924
2004-08-20,2.527778,2.729730,2.515015,2.710460,2.710460,456686856
2004-08-23,2.771522,2.839840,2.728979,2.737738,2.737738,365122512
2004-08-24,2.783784,2.792793,2.591842,2.624374,2.624374,304946748
2004-08-25,2.626627,2.702703,2.599600,2.652653,2.652653,183772044
...,...,...,...,...,...,...
2023-05-15,116.110001,118.480003,116.010002,116.510002,116.510002,36266800
2023-05-16,116.489998,120.750000,116.430000,119.510002,119.510002,45035600
2023-05-17,119.610001,121.669998,118.889999,120.839996,120.839996,33323600
2023-05-18,120.949997,123.309998,120.830002,122.830002,122.830002,35234200
2023-05-19,123.550003,125.970001,122.150002,122.760002,122.760002,41330300

In [ ]:
list_of_stocks[1]

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
1986-03-13,0.088542,0.101563,0.088542,0.097222,0.060524,1031788800
1986-03-14,0.097222,0.102431,0.097222,0.100694,0.062686,308160000
1986-03-17,0.100694,0.103299,0.100694,0.102431,0.063767,133171200
1986-03-18,0.102431,0.103299,0.098958,0.099826,0.062145,67766400
1986-03-19,0.099826,0.100694,0.097222,0.098090,0.061065,47894400
...,...,...,...,...,...,...
2023-05-15,309.100006,309.899994,307.589996,309.459991,308.784973,16336500
2023-05-16,309.829987,313.709991,309.829987,311.739990,311.059998,26730300
2023-05-17,312.290009,314.429993,310.739990,314.000000,314.000000,24315000
2023-05-18,314.529999,319.040009,313.720001,318.519989,318.519989,27276000
2023-05-19,316.739990,318.750000,316.369995,318.339996,318.339996,27529500

In [2]:
import yfinance as yf

In [3]:
def get_stock_info(ticker: str) -> dict:
    # Get More Data:
    tck = yf.Ticker(ticker)
    ALL_DATA = {
        'get stock info': tck.info,
        'get historical market data': tck.history(period="max"),
        'show actions (dividends, splits)': tck.actions,
        'show dividends': tck.dividends,
        'show splits': tck.splits,
        'show financials': [tck.financials, tck.quarterly_financials],
        'show balance sheet': [tck.balance_sheet, tck.quarterly_balance_sheet],
        'show cashflow': [tck.cashflow, tck.quarterly_cashflow],
        'show earnings': [tck.earnings, tck.quarterly_earnings],
        'show sustainability': tck.sustainability,
        'show analysts recommendations': tck.recommendations,
        'show next event (earnings, etc)': tck.calendar
    }

    return ALL_DATA

In [24]:
tck = yf.Ticker("AAPL")
all_info = {
        'get stock info': tck.info,
        'get historical market data': tck.history(period="max"),
        'show actions (dividends, splits)': tck.actions,
        'show dividends': tck.dividends,
        'show splits': tck.splits,
        # 'show financials': [tck.financials, tck.quarterly_financials],
        # 'show balance sheet': [tck.balance_sheet, tck.quarterly_balance_sheet],
        # 'show cashflow': [tck.cashflow, tck.quarterly_cashflow],
        # 'show earnings': [tck.earnings, tck.quarterly_earnings],
        # 'show sustainability': tck.sustainability,
        # 'show analysts recommendations': tck.recommendations,
        # 'show next event (earnings, etc)': tck.calendar
    }

In [43]:
import pandas as pd

In [50]:
short_info = all_info['get stock info']

In [51]:
the_stock_info = all_info['get stock info']
df = []
for key, value in the_stock_info.items():
    df.append([key,value])

df = pd.DataFrame(df)

In [47]:
pd.DataFrame(df)

                     0                   1
0             address1  One Apple Park Way
1                 city           Cupertino
2                state                  CA
3                  zip               95014
4              country       United States
..                 ...                 ...
125       grossMargins             0.43181
126      ebitdaMargins             0.32145
127   operatingMargins             0.29163
128  financialCurrency                 USD
129   trailingPegRatio              2.6825

[130 rows x 2 columns]